# Limpieza y Transformación de Datos con Python

Ejemplo práctico para Ciencia de Datos

In [1]:
import pandas as pd
import numpy as np

## 1. Crear datos con errores

In [2]:
data = {
    "nombre": ["Juan", "María", "Pedro", "Ana", "Luis", None],
    "edad": [25, 30, None, 22, 40, 35],
    "profesion": ["Ingeniero", "doctor", "Profesor", "Ingeniero", None, "doctor"],
    "sueldo": ["1000000", "1200000", None, "950000", "1100000", "1300000"]
}

df = pd.DataFrame(data)
print(df)

  nombre  edad  profesion   sueldo
0   Juan  25.0  Ingeniero  1000000
1  María  30.0     doctor  1200000
2  Pedro   NaN   Profesor      NaN
3    Ana  22.0  Ingeniero   950000
4   Luis  40.0        NaN  1100000
5    NaN  35.0     doctor  1300000

## 2. Exploración de datos

In [3]:
df.info() # explora la estructura del DataFrame, mostrando el número de entradas, el número de columnas, los nombres de las columnas, el tipo de datos de cada columna y la cantidad de valores no nulos en cada columna. Esta información es útil para entender la composición del DataFrame y detectar posibles problemas con los datos, como valores faltantes o tipos de datos incorrectos.
print("*" * 50)
df.isnull().sum() #

df

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   nombre     5 non-null      str
 1   edad       5 non-null      float64
 2   profesion  5 non-null      str
 3   sueldo     5 non-null      str
dtypes: float64(1), str(3)
memory usage: 324.0 bytes
**************************************************

  nombre  edad  profesion   sueldo
0   Juan  25.0  Ingeniero  1000000
1  María  30.0     doctor  1200000
2  Pedro   NaN   Profesor      NaN
3    Ana  22.0  Ingeniero   950000
4   Luis  40.0        NaN  1100000
5    NaN  35.0     doctor  1300000

## 3. Limpieza de datos

In [4]:
# Eliminar nulos en nombre
df = df.dropna(subset=["nombre"])

# Rellenar edad con promedio
df["edad"] = df["edad"].fillna(df["edad"].mean())

# Rellenar profesión
df["profesion"] = df["profesion"].fillna("Desconocido")

## 4. Transformación de datos

In [5]:
# Convertir sueldo a numérico
df["sueldo"] = pd.to_numeric(df["sueldo"], errors="coerce")

# Rellenar nulos con mediana
df["sueldo"] = df["sueldo"].fillna(df["sueldo"].median())

# Estandarizar texto
df["profesion"] = df["profesion"].str.lower()

# Crear categoría de edad
df["categoria_edad"] = pd.cut(df["edad"],
                             bins=[0, 30, 50, 100],
                             labels=["Joven", "Adulto", "Mayor"])

df

  nombre   edad    profesion     sueldo categoria_edad
0   Juan  25.00    ingeniero  1000000.0          Joven
1  María  30.00       doctor  1200000.0          Joven
2  Pedro  29.25     profesor  1050000.0          Joven
3    Ana  22.00    ingeniero   950000.0          Joven
4   Luis  40.00  desconocido  1100000.0         Adulto

## 5. Análisis simple

In [ ]:
# explicar por linea
df.groupby("profesion")["sueldo"].mean()

profesion
desconocido    1100000.0
doctor         1200000.0
ingeniero       975000.0
profesor       1050000.0
Name: sueldo, dtype: float64